# fly.toml app configuration file generated for green-forest-9671 on 2023-06-25T17:18:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-forest-9671"
primary_region = "phx"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
